#!/bin/bash

cd nccl

# module load cuda/11.6.2
# module load cuda/12.1.1
module load cuda/11.8.0
module list

make clean

# export NVTX_FLAGS="-DENABLE_NET_NVTX \
#  -DENABLE_NVTX_EVENT_NET_SEND_ENTRY -DENABLE_NVTX_EVENT_NET_SEND_EXIT -DENABLE_NVTX_EVENT_NET_RECV_ENTRY -DENABLE_NVTX_EVENT_NET_RECV_EXIT \
#  -DENABLE_NVTX_EVENT_NET_SEND_TEST_ENTRY -DENABLE_NVTX_EVENT_NET_SEND_TEST_EXIT -DENABLE_NVTX_EVENT_NET_RECV_TEST_ENTRY -DENABLE_NVTX_EVENT_NET_RECV_TEST_EXIT \
#  -DENABLE_NVTX_EVENT_NCCL_INIT_ENTRY -DENABLE_NVTX_EVENT_NCCL_INIT_EXIT"

export NVTX_FLAGS="-DENABLE_NET_NVTX \
 -DENABLE_NVTX_EVENT_NET_SEND_ENTRY -DENABLE_NVTX_EVENT_NET_SEND_EXIT -DENABLE_NVTX_EVENT_NET_RECV_ENTRY -DENABLE_NVTX_EVENT_NET_RECV_EXIT \
 -DENABLE_NVTX_EVENT_NET_SEND_TEST_ENTRY -DENABLE_NVTX_EVENT_NET_SEND_TEST_EXIT -DENABLE_NVTX_EVENT_NET_RECV_TEST_ENTRY -DENABLE_NVTX_EVENT_NET_RECV_TEST_EXIT"

make -j src.build CUDA_HOME=/apps/ault/spack/opt/spack/linux-centos8-zen/gcc-8.4.1/cuda-11.8.0-fjdnxm6yggxxp75sb62xrxxmeg4s24ml NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80" NVTX_FLAGS="$NVTX_FLAGS"
